steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/github.com/IanVaughan/hello-elixir-cloud-run",
        ".",
      ]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/github.com/IanVaughan/hello-elixir-cloud-run",
      ]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "{REPO_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/github.com/IanVaughan/hello-elixir-cloud-run",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/github.com/IanVaughan/hello-elixir-cloud-run
